### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by ImpureSilver11** [ImpureSilver11/ImpureSilver11.github.io#2]
真ん中寄せに

**Comment by ImpureSilver11** [comment]
上か横にメニュー作って分割させた方が良さげ

**Comment by takahashimasahiro** [comment]
メニューは他でも使えるようVueでコンポーネント化しておく。

**Comment by takahashimasahiro** [comment]
css周りはいい感じのモデルを探してみる

**Comment by ImpureSilver11** [comment]
なるほどデザインを読んだ。その上でどういう色使いにするべきかとかを考えていこうと思う。一旦ペライチでもどういう構造にするかアウトプットする

**Comment by ImpureSilver11** [comment]
ドラクエ好きだし、認知されやすいからドラクエ感欲しいな。(添付は参考のDQX画面)


![IMG_1868](https://user-images.githubusercontent.com/35370274/65371085-02692e80-dc9b-11e9-8fea-63e4af22a26d.JPG)
![IMG_1870](https://user-images.githubusercontent.com/35370274/65371087-02692e80-dc9b-11e9-8023-27b54ff0d824.JPG)
![IMG_1871](https://user-images.githubusercontent.com/35370274/65371088-0301c500-dc9b-11e9-98dc-3ff8eedc2722.PNG)

**Comment by ImpureSilver11** [comment]
DQ7辺りが私は大好きです。
https://www.google.com/search?rlz=1C5CHFA_enJP817JP821&biw=1680&bih=901&tbm=isch&sxsrf=ACYBGNQz4fZ5gy6416jikytU_vvM-jHJIQ%3A1569222060101&sa=1&ei=rG2IXbrgBcrR-QarkJ-4Dg&q=%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%887+%E5%85%88%E9%A0%AD%E7%94%BB%E9%9D%A2&oq=%E3%83%89%E3%83%A9%E3%82%B4%E3%83%B3%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%887+%E5%85%88%E9%A0%AD%E7%94%BB%E9%9D%A2&gs_l=img.3...9263.13711..14187...0.0..0.84.824.11......0....1..gws-wiz-img.aykNz7YxgdQ&ved=0ahUKEwi65tzbr-bkAhXKaN4KHSvIB-cQ4dUDCAc&uact=5

**Comment by ImpureSilver11** [comment]
・概要を乗せた一覧テーブルを作成
　-> それぞれの項目をホバーで別窓に詳細を表示
・ステータスはどうしようかな？
・スキルは⭐️数で表していいかも
    -> ただ階層構造は表しにくいから、そこは要検討
・SPAで作ってるところを活かして、数ページ作ってもいいかもね。

**Comment by ImpureSilver11** [comment]
古い経歴とナンバリング合わせてもいいかも

**Comment by ImpureSilver11** [comment]
ビッみょ
